version: 0.0
os: windows
files:
  - source: publish
    destination: C:\NGM\DEMO\NewDemoSite2
hooks:
  BeforeInstall:
    - location: \Scripts\before-install.bat
    - location: \Scripts\IisSetup.ps1
      timeout: 300
      runas: Administrator
  AfterInstall:
    - location: \Scripts\after-install.bat
      timeout: 300
