version: 0.0
os: windows
files:
  - source: publish
    destination: C:\NGM\DEMO\InstallPackage
    overwrite: true
hooks:
  BeforeInstall:
    - location: \DevOps\Scripts\before-install.bat
    - location: \DevOps\Scripts\IisSetup.ps1
      timeout: 300
      runas: Administrator
  AfterInstall:
    - location: \DevOps\Scripts\after-install.bat
      timeout: 300
