version: 0.0
os: windows
files:
  - source: AspnetCoreMvcDemo1/publish
    destination: C:\NGM\DEMO\NewDemoSite1
hooks:
  BeforeInstall:
    - location: \Scripts\before-install.bat
    - location: \Scripts\IisSetup.ps1
      timeout: 300
  AfterInstall:
    - location: \Scripts\after-install.bat
      timeout: 300
